urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from settings import MEDIA_ROOT
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', 'firedeptmanagement.common.views.base', name='base'),
                       url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT}),
                       url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
                       url(r'^logout/$', 'django.contrib.auth.views.logout_then_login', name='logout'),
                       url(r'^directorio/$', 'firedeptmanagement.capitalrelacional.views.search_related', name="directorio"),
                       
                       url(r'^sugerencias/$', 'firedeptmanagement.common.views.create_suggestion', name="create_suggestion"),
                       
                       url(r'^miperfil/$', 'firedeptmanagement.personal.views.user_profile', name="perfil"),
                       url(r'^perfil/(?P<ff_id>\d+)/$', 'firedeptmanagement.personal.views.user_profile', name="perfil_f"),
                       
                       url(r'^verplanilla/(?P<ff_id>\d+)/$', 'firedeptmanagement.personal.views.view_cnb_form', name="view_cnb_form"),
                       
                       #ADMIN
                       (r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

common/models.py
#coding=utf-8
from django.db import models
from firedeptmanagement.common.widgets import LocationField
from django.forms import ModelForm

class TelephoneNumber(models.Model):
    class Meta:
        verbose_name = u"Número Telefónico"
        verbose_name_plural = u'Números Telefónicos'
        
    code = models.CharField(max_length=4, verbose_name = u'Código')
    number = models.CharField(max_length=7, verbose_name = u'Número')
    
    def __unicode__(self):
        return "%s-%s" % (self.code, self.number)

class City(models.Model):
    class Meta:
        verbose_name = u"Ciudad"
        verbose_name_plural = u'Ciudades'

    name = models.CharField(max_length=250, verbose_name = u'Nombre')

    def __unicode__(self):
        return self.name

class Address(models.Model):
    class Meta:
        verbose_name = u"Dirección"
        verbose_name_plural = u'Direcciones'
    
    city = models.ForeignKey(City, verbose_name = u'Ciudad', null=True, blank=True)
    location = models.TextField(verbose_name = u'Detalle', null=True, blank=True)
    map_location = LocationField(verbose_name = u'Ubicación en Mapa',blank=True, max_length=255)

    def __unicode__(self):
        return self.location

class School(models.Model):
    class Meta:
        verbose_name = u"Institución Educativa"
        verbose_name_plural = u'Instituciones Educativas'
        
    
    name = models.CharField(verbose_name = u'Nombre', max_length=100)
    
    def __unicode__(self):
        return self.name

class Degree(models.Model):
    class Meta:
        verbose_name = u"Estudio"
    
    DEGREE_LEVEL_CHOICES = (
                            (u'TSU', u'Técnico Superior Universitario'),
                            (u'PREG', u'Pregrado (Licenciatura/Ingeniería)'),
                            (u'DIP', u'Diplomado'),
                            (u'ESP', u'Especialización'),
                            (u'MAES', u'Maestría'),
                            (u'DOCT', u'Doctorado'),
                            (u'PDOC', u'Postdoctorado'),
                            )
    
    name = models.CharField(verbose_name = u'Nombre', max_length=100)
    level = models.CharField(verbose_name = u'Tipo', max_length=4, choices=DEGREE_LEVEL_CHOICES) 
    school = models.ForeignKey(School,  verbose_name = u'Institución')
    
    def __unicode__(self):
        return "%s %s - %s" % (self.level, self.name, self.school.name) 

class Course(models.Model):
    class Meta:
        verbose_name = u"Curso"
    
    name = models.CharField(verbose_name = u'Nombre', max_length=100)
    school = models.ForeignKey(School,  verbose_name = u'Institución')
    hours = models.IntegerField()
    
    def __unicode__(self):
        return "%s (%d h) - %s" % (self.name, self.hours, self.school.name)

class Company(models.Model):
    class Meta:
        verbose_name = u"Compañia"
    
    name = models.CharField(verbose_name = u'Nombre', max_length=100)
    address = models.ForeignKey(Address, null=True, blank=True, verbose_name = 'Dirección')
    rif = models.CharField(verbose_name = u'RIF', null=True, blank=True, max_length=10)
    website = models.CharField(verbose_name = u'Página Web', null=True, blank=True, max_length=50)
    email = models.EmailField(null = True, blank = True, verbose_name = u'Email')
    
    def __unicode__(self):
        return self.name

class Job(models.Model):
    class Meta:
        verbose_name = u"Trabajo"
    
    company = models.ForeignKey(Company)
    title = models.CharField(u'Cargo', max_length=100)
    
    def __unicode__(self):
        return "%s - %s" % (self.title, self.company.name)

class BasePerson(models.Model):
    class Meta:
        verbose_name = u"Persona Min"
    
    GENDER_CHOICES = (
        (u'M', u'Masculino'),
        (u'F', u'Femenino'),
    )
    
    first_name = models.CharField(verbose_name = u'Primer Nombre', max_length=100)
    first_name_2 = models.CharField(verbose_name = u'Segundo Nombre', max_length=100, null=True, blank=True)
    last_name = models.CharField(verbose_name = u'Primer Apellido', max_length=100)
    last_name_2 = models.CharField(verbose_name = u'Segundo Apellido', max_length=100, null=True, blank=True)
    id_document = models.CharField(verbose_name = u'Cédula', max_length=10, null=True, blank=True)
    gender = models.CharField(verbose_name = u'Sexo', max_length=2, choices=GENDER_CHOICES, null=True, blank=True)
    primary_email = models.EmailField(null = True, blank = True, verbose_name = 'Email Principal')
    alternate_email = models.EmailField(null = True, blank = True, verbose_name = 'Email Alterno')
    
    def __unicode__(self):
        return "%s %s" % (self.first_name, self.last_name)

class PersonTelephoneNumber(models.Model):
    class Meta:
        verbose_name = u"Número Telefónico"
        verbose_name_plural = u'Números Telefónicos'
    
    TELEPHONE_TYPE_CHOICES = (
                         (u'T', u'Trabajo'),
                         (u'C', u'Casa'),
                         (u'M', u'Celular'),
                         (u'O', u'Otro'),
                         )
    
    person = models.ForeignKey(BasePerson)
    type = models.CharField(verbose_name = u'Tipo', max_length=1, choices=TELEPHONE_TYPE_CHOICES)
    telephone_number = models.ForeignKey(TelephoneNumber)
    main = models.BooleanField(verbose_name = 'Principal', default=True)
    
    def __unicode__(self):
        return self.get_type_display()+": "+str(self.telephone_number)

class CompanyTelephoneNumber(models.Model):
    class Meta:
        verbose_name = u"Número Telefónico"
        verbose_name_plural = u'Números Telefónicos'
    
    company = models.ForeignKey(Company)
    telephone_number = models.ForeignKey(TelephoneNumber)
    main = models.BooleanField(verbose_name = 'Principal', default=True)
    
    def __unicode__(self):
        return str(self.telephone_number)

    
class Person(BasePerson):
    class Meta:
        verbose_name = u"Persona"
    
    
    CIVIL_STATE_CHOICES = (
        (u'S', u'Soltero'),
        (u'C', u'Casado'),
        (u'V', u'Viudo'),
        (u'D', u'Divorciado'),
        
    )
    
    birth_date = models.DateField(verbose_name = u'Fecha de Nacimiento', null=True, blank=True)
    birth_place = models.OneToOneField(Address, related_name='born_here', verbose_name = 'Lugar de Nacimiento', null=True, blank=True)
    picture = models.ImageField(upload_to="images/persons/", null=True, blank=True, verbose_name = 'Foto')
    addresses = models.ManyToManyField(Address, verbose_name = u'Direcciones', through="PersonAddress", null=True)
    degrees = models.ManyToManyField(Degree, through="PersonDegree", null=True, verbose_name = u'Estudios')
    courses = models.ManyToManyField(Course, through="PersonCourse", null=True, verbose_name = u'Cursos')
    jobs = models.ManyToManyField(Job, through="PersonJob", null=True, verbose_name = u'Trabajos')
    childs = models.ManyToManyField(BasePerson, null=True, blank=True, verbose_name = u'Hijos', related_name="child_set")
    civil_state = models.CharField(verbose_name = u'Estado Civil', max_length=1, choices=CIVIL_STATE_CHOICES, null=True, blank=True)

class PersonAddress(models.Model):
    class Meta:
        verbose_name = u"Dirección"
    
    ADDRESS_TYPE_CHOICES = (
                            (u'C', u'Casa'),
                            (u'T', u'Trabajo'),
                            (u'O', u'Otro'),
                            )
    
    type = models.CharField(verbose_name = u'Tipo', max_length=1, choices=ADDRESS_TYPE_CHOICES)
    person = models.ForeignKey(Person, verbose_name = u'Persona')
    address = models.ForeignKey(Address, verbose_name = u'Dirección')

class PersonDegree(models.Model):
    class Meta:
        verbose_name = u"Estudio"
    
    person = models.ForeignKey(Person, verbose_name = u'Persona')
    degree = models.ForeignKey(Degree, verbose_name = u'Estudio')
    start_date = models.DateField(verbose_name = u'Fecha de Inicio')
    end_date = models.DateField(verbose_name = u'Fecha de Finalización', null=True, blank=True)
    picture = models.ImageField(upload_to="images/degrees/", null=True, blank=True, verbose_name = u'Imagen Título')
    
class PersonCourse(models.Model):
    class Meta:
        verbose_name = u"Curso"
    
    person = models.ForeignKey(Person, verbose_name = u'Persona')
    training_course = models.ForeignKey(Course, verbose_name = u'Curso')
    date = models.DateField(verbose_name = u'Fecha de Realización')
    picture = models.ImageField(upload_to="images/courses/", null=True, blank=True, verbose_name = u'Imagen Certificado')
    
class PersonJob(models.Model):
    class Meta:
        verbose_name = u"Trabajo"
    
    person = models.ForeignKey(Person, verbose_name = u'Persona')
    job = models.ForeignKey(Job, verbose_name = u'Trabajo')
    start_date = models.DateField(verbose_name = u'Fecha de Inicio')
    end_date = models.DateField(verbose_name = u'Fecha de Finalización', null=True, blank=True)
    supervisor = models.ForeignKey(BasePerson, null=True, blank=True, related_name =  'supervised_set', verbose_name = 'Supervisor')


class Suggestion(models.Model):
    date = models.DateTimeField(auto_now=True, verbose_name = u'Fecha')
    text = models.TextField(verbose_name = u'Sugerencia')

class SuggestionForm(ModelForm):
    class Meta:
        model = Suggestion

personal/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response
from personal.models import Firefighter

@login_required
def user_profile(request, ff_id=None):
    params = {} 
    if ff_id:
        firefighter = Firefighter.objects.get(id=ff_id)
    else:
        firefighter = request.user.get_profile()        
        
    params["firefighter"] = firefighter
    return render_to_response("perfil.html", params)

@login_required
def view_cnb_form(request, ff_id):
    firefighter = Firefighter.objects.get(id=ff_id)
    params = {"ff" : firefighter}    
    return render_to_response("planilla_cnb.html", params)

personal/templates/perfil.html
{%extends "base.html" %}

{%block content%}
<div>
	<div class="span-17">
		<div class="span-3">
			{%if firefighter.picture%}<img width="100px" height="120px"  src='{{firefighter.picture.url}}'></img>{%endif%}
		</div>
		<div class="last">
		<h2>
			{{firefighter.current_rank}} {{firefighter.first_name}} {{firefighter.first_name_2}} {{firefighter.last_name}} {{firefighter.last_name_2}}
		</h2>
		<h2>{%if firefighter.initials%}{{firefighter.initials}}{%endif%} #{{firefighter.number}} </h2>
		</div>
	</div>
	<div class="span-8">
		<h3>Datos Básicos</h3>
		<ul>
			<li>Cedula: <strong>{{firefighter.id_document}}</strong></li>
			<li>Fecha de Nacimiento: <strong>{{firefighter.birth_date}}</strong></li>
			<li>Sexo: <strong>{{firefighter.gender}}</strong></li>
			<li>Sangre: <strong>Factor {{firefighter.blood_type}} Rh {{firefighter.blood_type_rh}}</strong></li>
		</ul>
		
	</div>
	<div class="span-8 last">
		<h3>Datos de Contacto:</h3>
		<ul>
			{%for phone in firefighter.persontelephonenumber_set.all %}
				<li>{{phone}}</li>
			{%endfor%}
			
			<li>Email: {{firefighter.primary_email}}</li>
			<li>Email: {{firefighter.alternate_email}}</li>
		</ul>
	</div>
</div>
{%endblock%}

personal/templates/planilla_cnb.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title></title>
		<style type="text/css">
			.form_text {
				font-family: Arial;
				font-size: 2em;
			}
			
			body
			{
			background:url(/static/images/planilla_cnb.jpg) no-repeat ;
			}
			
		</style>
	</head>
	<body>
		<div style="position: absolute;top: 280px;left: 150px;" class="form_text">{{ff.first_name}}&nbsp;{{ff.first_name_2|default_if_none:""}}</div>
		<div style="position: absolute;top: 340px;left: 150px;" class="form_text">{{ff.last_name}}&nbsp; {{ff.last_name_2|default_if_none:""}}</div>
		<div style="position: absolute;top: 400px;left: 300px;" class="form_text">{{ff.id_document}}</div>
		<div style="position: absolute;top: 600px;left: 830px;" class="form_text">{{ff.blood_type}}Rh{{ff.blood_type_rh}}</div>
		<div style="position: absolute;top: 680px;left: 300px;" class="form_text">{{ff.addresses.all.0.city}}</div>
		<div style="position: absolute;top: 720px;left: 50px;width: 800px;" class="form_text">{{ff.addresses.all.0.location}}</div>
		<div style="position: absolute;top: 840px;left:300px;" class="form_text">
			{%for phone in ff.persontelephonenumber_set.all %}
				{{phone}}
			{%endfor%}
		</div>
		<div style="position: absolute;top: 880px;left:250px;" class="form_text">
			{{ff.primary_email}}<br />
			{{ff.alternate_email}}
		</div>
		<div style="position: absolute;top: 1040px;left: 150px;" class="form_text">{{ff.gender}}</div>
		
		
		<div style="position: absolute;top:10px;left:990px;">.</div>
		<div style="position: absolute;top:1220px;left:990px;">.</div>
		{%if ff.picture%}<img width="200px" height="270px" style="position: absolute;top:300px;left:760px;"  src='{{ff.picture.url}}'></img>{%endif%}
	</body>
</html>